export const THEME_CONTRACT_SELECTORS = [':root', '.dark', '.theme-monokai'] as const;

export const THEME_CONTRACT_TOKENS = [
  'accent',
  'accent-foreground',
  'background',
  'border',
  'card',
  'card-foreground',
  'destructive',
  'destructive-foreground',
  'foreground',
  'input',
  'muted',
  'muted-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'radius',
  'review-code-text',
  'review-comment-cell-bg',
  'review-file-bg',
  'review-file-border',
  'review-gutter-bg',
  'review-gutter-border',
  'review-gutter-hover-bg',
  'review-gutter-hover-text',
  'review-gutter-text',
  'review-header-border',
  'review-header-text',
  'review-row-border',
  'review-row-comment-bg',
  'review-row-select-bg',
  'ring',
  'scrollbar-thumb',
  'scrollbar-thumb-hover',
  'scrollbar-track',
  'secondary',
  'secondary-foreground',
  'ui-slate-100',
  'ui-slate-200',
  'ui-slate-300',
  'ui-slate-400',
  'ui-slate-500',
  'ui-slate-600',
  'ui-slate-700',
  'ui-slate-800',
  'ui-slate-900',
  'ui-slate-950',
] as const;

export type ThemeContractToken = (typeof THEME_CONTRACT_TOKENS)[number];
